default: &default
  adapter: postgresql
  encoding: unicode
  
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: unter_challenge_development

test:
  <<: *default
  database: unter_challenge_test

production:
  <<: *default
  database: unter_challenge_production
  username: unter_challenge
  password: <%= ENV['UNTER_CHALLENGE_DATABASE_PASSWORD'] %>
